---
 - name: install radvd
   apt:
     name: "{{ item }}"
   with_items:
     - radvd
     - wide-dhcpv6-client

 - name: ensure ipv6 forwarding is enabled for new interfaces
   sysctl:
     name: "net.ipv6.conf.{{item}}.forwarding"
     value: 1
   with_items:
     - all
     - default

 - name: ensure ipv6 forwarding is enabled for existing interfaces
   lineinfile:
     dest: "/etc/sysctl.d/99-ipv6-forwarding.conf"
     create: yes
     owner: root
     group: root
     mode: 0444
     line: "net.ipv6.conf.{{item|replace('.','/')}}.forwarding=1"
   with_items: "{{ ansible_interfaces|reject('equalto', 'lo')|sort }} "
   register: sysctl_reload

 - name: reload ipv6 forwarding sysctls
   command: /sbin/sysctl -w "net.ipv6.conf.{{item|replace('.','/')}}.forwarding=1"
   with_items: "{{ ansible_interfaces|reject('equalto', 'lo')|sort }} "
   when: sysctl_reload.changed

 - name: install radvd conf
   copy:
     src: radvd.conf
     dest: /etc/radvd.conf
   notify: radvd_service

 - name: generate wide-dhcpv6-client interface defaults
   template:
     src: wide-dhcpv6-client.j2
     dest: /etc/default/wide-dhcpv6-client
   notify: wide-dhcpv6-client_service

 - name: generate wide-dhcpv6-client configuration
   template:
     src: dhcp6c.conf.j2
     dest: /etc/wide-dhcpv6/dhcp6c.conf
   notify: wide-dhcpv6-client_service

 - name: copy wide-dhcpv6-client ifupdown script
   copy:
     src: dhcp6c-ifupdown
     dest: /etc/wide-dhcpv6/dhcp6c-ifupdown
     owner: root
     group: root
     mode: 0555
   notify: wide-dhcpv6-client_service

 - name: ensure radvd comes up at boot
   service:
     name: "{{ item }}"
     enabled: true
     state: started
   with_items:
     - wide-dhcpv6-client
     - radvd
